#version 450

layout (local_size_x = 16, local_size_y = 16) in;
layout (binding = 0, rgba8) uniform readonly image2D inputImage;
layout (binding = 1, rgba8) uniform image2D resultImage;

void main()
{   
    ivec2 pixelCoords = ivec2(gl_GlobalInvocationID.xy);

    vec3 rgb = imageLoad(inputImage, pixelCoords).rgb;  
                                    
    vec4 pixel = vec4(rgb, 1.0);

    imageStore(resultImage, pixelCoords, pixel);
}