#version 450

layout (local_size_x = 16, local_size_y = 16) in;
layout (binding = 0, rgba8) uniform readonly image2D inputImage;
layout (binding = 1, rgba8) uniform image2D resultImage;

void main()
{   
    ivec2 pixelCoords = ivec2(gl_GlobalInvocationID.xy);

    vec4 pixel = imageLoad(inputImage, pixelCoords).rgba;  

    if (pixel.a > 0)
    {
        pixel = vec4(pixel.rgb / pixel.a, pixel.a);
    }

    imageStore(resultImage, pixelCoords, pixel);
}